### ISSUE TITLE
Git hooks

### ISSUE THREAD

**Issue by eozd** [ktrianta/jacobi-svd-evd#13]
We need to incorporate git hooks into the project to automatically format the committed codes, and possibly lint the code (maybe cpplint ?).

**Comment by ktrianta** [comment]
Good idea. A pre-commit hook (or two) would do, right?

**Comment by eozd** [comment]
We can use a pre-commit hook to format the codes using clang-format. We can also another hook to run cpplint and disable the commit if it doesn't conform to the standards. I can also put cpplint to travis configuration so that the build fails for codes that don't pass cpplint checks.

**Comment by ktrianta** [comment]
If you have the time to do this, it would be perfect!
